name: PHPCS check Pull Request

on: pull_request

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout (official)
      - uses: actions/checkout@v2

      # https://github.com/chekalsky/phpcs-action (community)
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true
          installed_paths: '${{ github.workspace }}/vendor/squizlabs/php_codesniffer'
          phpcs_bin_path: './vendor/bin/phpcs'
