name: PHPCS check

on:
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
  workflow_dispatch:

env:
  PHP_VERSION: '7.3'

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 1

        - name: Setup PHP ${{ env.PHP_VERSION }}
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ env.PHP_VERSION }}

        - name: Install Composer Dependencies
          run: composer install --no-progress --prefer-dist --optimize-autoloader

        - name: PHPCS check
          uses: chekalsky/phpcs-action@v1
          with:
            phpcs_bin_path: './vendor/bin/phpcs'
