name: PHPCS check

on:
  pull_request:
  workflow_dispatch:

env:
  PHP_VERSION: '7.3'

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout (official)
      - uses: actions/checkout@v3

      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP ${{ env.PHP_VERSION }} with cs2pr
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          tools: composer, cs2pr

      # Composer
      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

        # https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: PHPCS check pull_request
        if: ${{ github.event_name == 'pull_request' }}
        run: ./vendor/bin/phpcs --standard=phpcs.xml ./ -q --report=checkstyle | cs2pr --graceful-warnings

      - name: PHPCS check workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: composer phpcs -- --colors
